language: c

os:
  - osx

osx_image: xcode11.3

compiler:
  - gcc

cache: ccache

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --HEAD https://raw.githubusercontent.com/theori-io/nrsc5/master/nrsc5.rb; fi

before_script:

script:
  - xz -d < support/sample.xz > sample
  - nrsc5 -r sample -o sample.wav 0 2> sample.log
  - cat sample.log
  - grep -q "You're Listening to Q" sample.log
  - cat sample | nrsc5 -r - -o sample.wav 0 2> sample.log
  - grep -q "You're Listening to Q" sample.log
